"""add_project_background_fields

Revision ID: 9096cebbd688
Revises: d709ad1bbe2f
Create Date: 2026-06-14 17:18:17.366672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9096cebbd688'
down_revision: Union[str, Sequence[str], None] = 'd709ad1bbe2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('avoid_image_generation', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('projects', sa.Column('background_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'background_image_url')
    op.drop_column('projects', 'avoid_image_generation')
    # ### end Alembic commands ###
