"""add_slide_hook_type_caption_emoji

Revision ID: d709ad1bbe2f
Revises: 9e512aef0704
Create Date: 2026-06-12 21:53:11.288323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd709ad1bbe2f'
down_revision: Union[str, Sequence[str], None] = '9e512aef0704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('slides', sa.Column('hook_type', sa.String(), nullable=True))
    op.add_column('slides', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('slides', sa.Column('emoji', sa.String(length=10), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('slides', 'emoji')
    op.drop_column('slides', 'caption')
    op.drop_column('slides', 'hook_type')
    op.alter_column('articles', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
